export const MovieGenres: Map<string, number> = new Map([
    ["Akcja", 0],
    ["Animowany", 1],
    ["Biograficzny", 2],
    ["Dramat", 3],
    ["Familijny", 4],
    ["Fantasy", 5],
    ["Horror", 6],
    ["Komedia", 7],
    ["Komedia romantyczna", 8],
    ["Kryminał", 9],
    ["Musical", 10],
    ["Obyczajowy", 11],
    ["Przygodowy", 12],
    ["Romans", 13],
    ["Science Fiction", 14],
    ["Sensacyjny", 15],
    ["Thriller", 16],
    ["Fantastyka", 17]
])